FROM jenkins/jenkins:lts

USER root

# Instalar o Docker Compose
RUN apt-get update && apt-get install -y curl \
    && curl -L "https://github.com/docker/compose/releases/download/v2.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose \
    && chmod +x /usr/bin/docker-compose

# Criar o grupo 'docker' e adicionar o usuário 'jenkins' ao grupo
RUN groupadd docker \
    && usermod -aG docker jenkins

USER jenkins
